'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
def fib(n):
    if n==1:
        return 1
    elif n==2:
        return 2    
    else:
        return fib(n-2)+fib(n-1)    

i=1
sum=0
while fib(i) <= 4000000:
    if fib(i)%2==0:
        sum=sum+fib(i)
        #print(sum)
    i=i+1    

print(sum)           
